BEGIN;

ALTER TABLE news ADD COLUMN IF NOT EXISTS event_type VARCHAR(64);
ALTER TABLE news ADD COLUMN IF NOT EXISTS event_tags TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS themes TEXT;
ALTER TABLE news ADD COLUMN IF NOT EXISTS impact_direction VARCHAR(32);
ALTER TABLE news ADD COLUMN IF NOT EXISTS nlp_confidence DOUBLE PRECISION;
ALTER TABLE news ADD COLUMN IF NOT EXISTS nlp_version VARCHAR(32);
ALTER TABLE news ADD COLUMN IF NOT EXISTS keywords TEXT;

COMMIT;
